name: CI
on:
  workflow_dispatch:
  schedule:
  - cron: 0 0 * * *
jobs:
  awesome-stars:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    name: Update awesome-stars
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        git clone https://github.com/ductnn/starred.git
        cd starred
        python setup.py install

    - name: Update repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: starred --username ductnn --repository awesome-stars --sort --token ${GITHUB_TOKEN} --message 'Update new stars'
